name: bex
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen: ^5.0.3

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1

  flutter_lints: ^2.0.0
  woocommerce_api: ^0.1.0
  gradient_borders: ^0.2.0
  dotted_border: ^2.0.0+3
  flutter_rating_bar: 4.0.1
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  go_router: ^5.1.1
  flutter_layout_grid: 2.0.1
  rxdart: ^0.27.7
  flutter_riverpod: ^2.0.2
  sembast: ^3.3.1
  path_provider: ^2.0.11
  freezed_annotation: 2.1.0
  sembast_web: ">=1.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/images/testimage.jpeg

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 400
